src/tcms/search/urls.py
# -*- coding: utf-8 -*-

from django.urls import path

from . import views

urlpatterns = [
    path("", views.advance_search, name="advanced-search"),
]

src/tcms/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog

# XML RPC handler
from kobo.django.xmlrpc.views import XMLRPCHandlerFactory

from tcms.core import ajax as tcms_core_ajax
from tcms.testruns import views as testruns_views

xmlrpc_handler = XMLRPCHandlerFactory("TCMS_XML_RPC")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("", include("tcms.core.urls")),
    path("", include("tcms.management.urls")),
    # Testplans zone
    path("plan/", include("tcms.testplans.urls.plan_urls")),
    path("plans/", include("tcms.testplans.urls.plans_urls")),
    # Testcases zone
    path("case/", include("tcms.testcases.urls.case_urls")),
    path("cases/", include("tcms.testcases.urls.cases_urls")),
    # Testruns zone
    path("run/", include("tcms.testruns.urls.run_urls")),
    path("runs/", include("tcms.testruns.urls.runs_urls")),
    path("accounts/", include("tcms.profiles.urls")),
    path("linkref/", include("tcms.linkreference.urls")),
    path("comments/", include("tcms.comments.urls")),
    path("advance-search/", include("tcms.search.urls")),
    path("report/", include("tcms.report.urls")),
    path("xmlrpc/", xmlrpc_handler),
    path("tinymce/", include("tinymce.urls")),
    # Using admin js without admin permission
    # refer: https://docs.djangoproject.com/en/1.6/topics/i18n/translation/#module-django.views.i18n
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
]

# Debug zone

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

# Overwrite default 500 handler
# More details could see django.core.urlresolvers._resolve_special()
handler500 = "tcms.core.views.error.server_error"

src/tcms/report/forms.py
# -*- coding: utf-8 -*-
from django import forms

from tcms.core.forms.fields import ModelChoiceField
from tcms.management.models import Component, Product, TestBuild, Version
from tcms.testcases.models import TestCaseCategory


class CustomSearchForm(forms.Form):
    pk__in: forms.ModelChoiceField = forms.ModelMultipleChoiceField(
        label="Build",
        queryset=TestBuild.objects.none(),
        required=False,
    )
    product = ModelChoiceField(
        label="Product",
        queryset=Product.objects.only("name").order_by("name"),
        empty_label=None,
        error_messages={
            "required": "Product is required to generate this report.",
            "invalid_pk_value": "%(pk)s is not a valid product ID for generating this report.",
        },
    )
    build_run__product_version = forms.ModelChoiceField(
        label="Product version",
        queryset=Version.objects.none(),
        required=False,
    )
    build_run__plan__name__icontains = forms.CharField(
        label="Plan name",
        required=False,
    )
    testcaserun__case__category = forms.ModelChoiceField(
        label="Case category",
        queryset=TestCaseCategory.objects.none(),
        required=False,
    )
    testcaserun__case__component = forms.ModelChoiceField(
        label="Case component",
        queryset=Component.objects.none(),
        required=False,
    )

    def populate(self, product_id):
        f_product_version = self.fields["build_run__product_version"]
        f_case__category = self.fields["testcaserun__case__category"]
        f_case__component = self.fields["testcaserun__case__component"]
        if product_id:
            f_product_version.queryset = Version.objects.filter(product__id=product_id).only(
                "value"
            )
            self.fields["pk__in"].queryset = TestBuild.objects.filter(product__id=product_id).only(
                "name"
            )
            f_case__category.queryset = TestCaseCategory.objects.filter(
                product__id=product_id
            ).only("name")
            f_case__component.queryset = Component.objects.filter(product__id=product_id).only(
                "name"
            )
        else:
            # FIXME: is this branch necessary? when I notice this, I'm
            # optimizing custom report here. If product_id is None, it's an
            # critical error for the search operation and everything should be
            # stopped. Therefor, in my opinion, following 4 lines of code
            # waste time and resources.
            f_product_version.queryset = Version.objects.only("value")
            self.fields["pk__in"].queryset = TestBuild.objects.only("name")
            f_case__category.queryset = TestCaseCategory.objects.only("name")
            f_case__component.queryset = Component.objects.only("name")


class CustomSearchDetailsForm(CustomSearchForm):
    pk__in = ModelChoiceField(
        label="Build",
        queryset=TestBuild.objects.none(),
        error_messages={
            "required": "A build is required to generate this report.",
            "invalid_pk_value": "%(pk)s is not a valid test build ID for generating this report.",
        },
    )

    def clean_build_run__product_version(self):
        return None


REPORT_TYPES = (
    ("per_build_report", "By Case-Run Tester"),
    ("per_priority_report", "By Case Priority"),
    ("runs_with_rates_per_plan_tag", "By Plan's Tag"),
    ("per_plan_tag_report", "By Plan's Tag Per Tag View"),
    ("runs_with_rates_per_plan_build", "By Plan & Build"),
    ("per_plan_build_report", "By Plan & Build Per Plan View"),
)


class BasicTestingReportFormFields(forms.Form):
    """Testing report form with basic necessary fields"""

    r_product = ModelChoiceField(
        required=True,
        label="Product",
        empty_label=None,
        queryset=Product.objects.only("name").order_by("name"),
        error_messages={
            "required": "You have to select a product to generate this testing report.",
            "invalid_pk_value": "%(pk)s is not a valid product.",
        },
        widget=forms.Select(
            attrs={
                "id": "r_product",
            }
        ),
    )

    r_build = forms.ModelMultipleChoiceField(
        required=False,
        label="Build",
        queryset=TestBuild.objects.none(),
        error_messages={
            "invalid_pk_value": "%s is not a valid test build ID.",
            "invalid_choice": "Test build ID %s does not exist.",
        },
        widget=forms.SelectMultiple(
            attrs={
                "id": "r_build",
                "size": "5",
            }
        ),
    )

    r_version = forms.ModelMultipleChoiceField(
        required=False,
        label="Version",
        queryset=Version.objects.none(),
        error_messages={
            "invalid_choice": "Version ID %s does not exist.",
            "invalid_pk_value": "%s is not a valid version ID.",
        },
        widget=forms.SelectMultiple(
            attrs={
                "id": "r_version",
                "size": "5",
            }
        ),
    )

    r_created_since = forms.DateField(
        required=False,
        input_formats=["%Y-%m-%d"],
        error_messages={
            "invalid": "The start execute date is invalid. The valid format is YYYY-MM-DD.",
        },
        widget=forms.TextInput(
            attrs={
                "id": "r_created_since",
                "style": "width:130px;",
                "class": "vDateField",
            }
        ),
    )

    r_created_before = forms.DateField(
        required=False,
        input_formats=["%Y-%m-%d"],
        error_messages={
            "invalid": "The end execute date is invalid. The valid format is YYYY-MM-DD.",
        },
        widget=forms.TextInput(
            attrs={
                "id": "r_created_before",
                "style": "width:130px;",
                "class": "vDateField",
            }
        ),
    )

    def populate(self, product_id):
        if product_id:
            self.fields["r_build"].queryset = TestBuild.objects.filter(product=product_id).only(
                "name"
            )
            self.fields["r_version"].queryset = Version.objects.filter(product=product_id).only(
                "value"
            )
        else:
            self.fields["r_build"].queryset = TestBuild.objects.none()
            self.fields["r_version"].queryset = Version.objects.none()


class TestingReportCaseRunsListForm(BasicTestingReportFormFields):
    """Form validation for viewing case runs from tesing report"""

    run = forms.IntegerField(
        required=False,
        min_value=1,
        error_messages={
            "invalid": "Run ID is not valid.",
            "min_value": "%(limit_value)s is not valid. Run ID should be an "
            "integer that is greater than 0.",
        },
    )

    priority = forms.IntegerField(
        required=False,
        min_value=1,
        error_messages={
            "invalid": "Priority ID is not valid.",
            "min_value": "%(limit_value)s is not valid. Priority ID should "
            "be an integer that is greater than 0.",
        },
    )

    tester = forms.IntegerField(
        required=False,
        min_value=0,
        error_messages={
            "invalid": "User ID is not valid.",
            "min_value": "%(limit_value)s is not valid. User ID should be an"
            " integer that is greater than and equal to 0",
        },
    )

    # Whatever the status name is passed from client, it doesn't matter. When
    # pass an invalid status name, no data will be queried.
    status = forms.CharField(
        required=False,
        max_length=30,
        error_messages={
            "max_length": "Are you sure this is the status name you want?",
        },
    )

    plan_tag = forms.CharField(
        required=False,
        max_length=30,
        error_messages={
            "max_length": "Are your sure this is the tag you want?",
        },
    )


class TestingReportForm(BasicTestingReportFormFields):
    """Criteria for generating testing report"""

    report_type = forms.ChoiceField(
        required=True,
        choices=REPORT_TYPES,
        initial="per_build_report",
        error_messages={
            "invalid_choice": "%(value)s is not a valid report type.",
        },
        widget=forms.RadioSelect,
    )

src/tcms/core/views/search.py
# -*- coding: utf-8 -*-

import re

from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.http import require_GET

from tcms.testcases.models import TestCase
from tcms.testplans.models import TestPlan
from tcms.testruns.models import TestRun


@require_GET
def search(request):
    """
    Redirect to correct url of the search content
    """

    models = {"plans": TestPlan, "cases": TestCase, "runs": TestRun}

    search_content = request.GET.get("search_content")
    search_type = request.GET.get("search_type")

    if not search_content or not search_type:
        raise Http404

    if search_type not in models:
        raise Http404

    try_to_get_object = re.match(r"^\d+$", search_content) is not None
    model = models[search_type]

    if try_to_get_object:
        pk = int(search_content)
        objects = model.objects.filter(pk=pk).only("pk")
        if objects:
            return HttpResponseRedirect(
                reverse(
                    "{}-get".format(model._meta.app_label.strip("s").replace("test", "")),
                    args=[pk],
                )
            )

    url = "{}?a=search&search={}".format(
        reverse("{}-all".format(model._meta.app_label.replace("test", ""))),
        search_content,
    )
    return HttpResponseRedirect(url)

src/templates/search/advanced_search.html
{% extends "tcms_base.html" %}
{% load static %}
{% block subtitle %}Advanced Search{% endblock %}

{% block custom_javascript %}
<script type="text/javascript" src="{% static "js/nitrate.advanced-search.js" %}"></script>
<script type="text/javascript" src="{% static "js/nitrate.testplans.js" %}"></script>
<script type="text/javascript" src="/jsi18n/"></script>
<script type="text/javascript" src="{% static "admin/js/core.js" %}"></script>
<script type="text/javascript" src="{% static "admin/js/calendar.js" %}"></script>
<script type="text/javascript" src="{% static "admin/js/admin/DateTimeShortcuts.js" %}"></script>
{% endblock %}

{% block contents %}
	<div class="sprites crumble">
		<a href="{% url "nitrate-index" %}">Home</a>
		>> Advanced Search
	</div>
	<div class="advancedSearchTip advancedSearch">
		<h3>Use the form below as your advanced search：</h3>
		<ul>
			<li>By selecting 'contains' or 'not contains' to include or exclude the tagged results.</li>
			<li>'Actual Tester' indicates the tester of case in a test run, may differ from 'default tester' of test run.</li>
			<li>Relationship Query :
				<p>Any of the three can be used to search one another：</p>
				<p>e.g. Select product 'RHEL6' in plan form,  and set 'Tom' as test run's manager, then search test plan .The result will be the plans under 'RHEL6' and have runs managed by 'Tom'.</p>
			</li>
		</ul>
	</div>
	<div class="itemSearch advancedSearch">
		<form action="{% url "advanced-search" %}" method="get" id="frmSearch">
		{% if errors %}
			<ul>
				<li>Errors -</li>
				{% for k, v in errors %}
				<li>{{ k|title }}: {{ v }}</li>
				{% endfor %}
			</ul>
		{% endif %}
		<div class="planCaseRun">
			<div class="containerTabGrey">
				<div class="top">
					<h3>Plan</h3>
				</div>
				<div class="content">
					<div class="listinfo">
						<div class="title"><label>Product&nbsp;:</label></div>
						<div class="listinfo_input">
							<select name="pl_product" id="pl_product" multiple="multiple" size="5">
								{% for p in products %}
								<option value="{{ p.pk }}">{{ p.name }}</option>
								{% endfor %}
							</select>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Component&nbsp;:</label></div>
						<div class="listinfo_input">
							<select name="pl_component" id="pl_component" multiple="multiple" size="5"></select>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Version&nbsp;:</label></div>
						<div class="listinfo_input">
							<select name="pl_version" id="pl_version" multiple="multiple" size="5"></select>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"><label>ID&nbsp;:</label></div>
						<div class="listinfo_input"><input type="text" name="pl_id"/></div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Summary&nbsp;:</label></div>
						<div class="listinfo_input"><input type="text" name="pl_summary"/></div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Plan Type&nbsp;:</label></div>
						<div class="listinfo_input">
							<select name="pl_type" multiple="multiple" size="5">
								{% for t in plan_types %}
								<option value="{{ t.pk }}">{{ t.name }}</option>
								{% endfor %}
							</select>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Author&nbsp;:</label></div>
						<div class="listinfo_input"><input type="text" name="pl_authors"/></div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Owner&nbsp;:</label></div>
						<div class="listinfo_input"><input type="text" name="pl_owners"/></div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Tag&nbsp;:</label></div>
						<div class="listinfo_input">
							<input type="text" style="width:130px;" name="pl_tags"/>
							<select name="pl_tags_exclude" style="width:116px;">
								<option value="false">Contains</option>
								<option value="true">Not Contains</option>
							</select>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Active&nbsp;:</label></div>
						<div class="listinfo_input">
							<ul>
								<li>
									<select name="pl_active">
										<option value="">--</option>
										<option value="yes">Active</option>
										<option value="no">Inactive</option>
									</select>
								</li>
							</ul>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Create Time&nbsp;:</label></div>
						<div class="listinfo_input">
								<input type="text" name="pl_created_since" style="width:130px;" class="vDateField"/>
								<a href="javascript:DateTimeShortcuts.openCalendar(0);" id="calendarlink1"></a>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"></div>
						<div class="listinfo_input">
								<input type="text" name="pl_created_before" style="width:130px;" class="vDateField"/>
								<a href="javascript:DateTimeShortcuts.openCalendar(0);" id="calendarlink1"></a>
						</div>
					</div>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div>
			<div class="containerTabGrey">
				<div class="top">
					<h3>Case</h3>
				</div>
				<div class="content">
					<div class="listinfo">
						<div class="title"><label>Product&nbsp;:</label></div>
						<div class="listinfo_input">
							<select name="cs_product" id="cs_product" multiple="multiple" size="5">
								{% for p in products %}
								<option value="{{ p.pk }}">{{ p.name }}</option>
								{% endfor %}
							</select>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Component&nbsp;:</label></div>
						<div class="listinfo_input">
							<select name="cs_component" id="cs_component" multiple="multiple" size="5"></select>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Category&nbsp;:</label></div>
						<div class="listinfo_input">
							<select name="cs_category" id="cs_category" multiple="multiple" size="5"></select>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"><label>ID&nbsp;:</label></div>
						<div class="listinfo_input"><input type="text" name="cs_id"/></div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Summary&nbsp;:</label></div>
						<div class="listinfo_input"><input type="text" name="cs_summary"/></div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Author&nbsp;:</label></div>
						<div class="listinfo_input"><input type="text" name="cs_authors"/></div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Default Tester&nbsp;:</label></div>
						<div class="listinfo_input"><input type="text" name="cs_tester"/></div>
					</div>
						<div class="listinfo">
						<div class="title"><label>Tag&nbsp;:</label></div>
						<div class="listinfo_input">
							<input type="text" style="width:130px;" name="cs_tags"/>
							<select name="cs_tags_exclude" style="width:116px;">
								<option value="false">Contains</option>
								<option value="true">Not Contains</option>
							</select>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Issue Key&nbsp;:</label></div>
						<div class="listinfo_input"><input type="text" name="cs_issues"/></div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Status&nbsp;:</label></div>
						<div class="listinfo_input">
							<ul>
								<li><input type="checkbox" name="cs_status" value="1" /><span>Proposed</span></li>
								<li><input type="checkbox" name="cs_status" value="2" /><span>Comfirmed</span></li>
							</ul>
							<ul>
								<li><input type="checkbox" name="cs_status" value="3" /><span>Disabled</span></li>
								<li><input type="checkbox" name="cs_status" value="4" /><span>Need_update</span></li>
							</ul>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Automated&nbsp;:</label></div>
						<div class="listinfo_input">
							<ul>
								<li>
									<select name="cs_auto">
										<option value="">--</option>
										<option value="yes">Automated</option>
										<option value="no">Manual</option>
									</select>
								</li>
							</ul>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Auto Proposed&nbsp;:</label></div>
						<div class="listinfo_input">
							<ul>
								<li>
									<select name="cs_proposed">
										<option value="">--</option>
										<option value="yes">Auto Proposed</option>
										<option value="no">Non Auto Proposed</option>
									</select>
								</li>
							</ul>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Priority&nbsp;:</label></div>
						<div class="listinfo_input">
							<ul>
								{% for priority in priorities.iterator %}
								<li><input type="checkbox" name="cs_priority" value="{{ priority.pk }}" /><span>{{ priority.value }}</span></li>
								{% endfor %}
							</ul>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Script&nbsp;:</label></div>
						<div class="listinfo_input"><input type="text" name="cs_script"/></div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Create Time&nbsp;:</label></div>
						<div class="listinfo_input">
								<input type="text" name="cs_created_since" style="width:130px;" class="vDateField"/>
								<a href="javascript:DateTimeShortcuts.openCalendar(1);" id="calendarlink1"></a>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"></div>
						<div class="listinfo_input">
								<input type="text" name="cs_created_before" style="width:130px;" class="vDateField"/>
								<a href="javascript:DateTimeShortcuts.openCalendar(1);" id="calendarlink1"></a>
						</div>
					</div>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div>
			<div class="containerTabGrey">
				<div class="top">
					<h3>Run</h3>
				</div>
				<div class="content">
					<div class="listinfo">
						<div class="title"><label>Product&nbsp;:</label></div>
						<div class="listinfo_input">
							<select name="r_product" id="r_product" multiple="multiple" size="5">
								{% for p in products %}
								<option value="{{ p.pk }}">{{ p.name }}</option>
								{% endfor %}
							</select>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Version&nbsp;:</label></div>
						<div class="listinfo_input">
							<select name="r_version" id="r_version" multiple="multiple" size="5"></select>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Build&nbsp;:</label></div>
						<div class="listinfo_input">
							<select name="r_build" id="r_build" multiple="multiple" size="5"></select>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"><label>ID&nbsp;:</label></div>
						<div class="listinfo_input"><input type="text" name="r_id"/></div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Summary&nbsp;:</label></div>
						<div class="listinfo_input"><input type="text" name="r_summary"/></div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Manager&nbsp;:</label></div>
						<div class="listinfo_input"><input type="text" name="r_manager"/></div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Default Tester&nbsp;:</label></div>
						<div class="listinfo_input"><input type="text" name="r_tester"/></div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Actual Tester&nbsp;:</label></div>
						<div class="listinfo_input"><input type="text" name="r_real_tester"/></div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Tag&nbsp;:</label></div>
						<div class="listinfo_input">
							<input type="text" style="width:130px;" name="r_tags"/>
							<select name="r_tags_exclude" style="width:116px;">
								<option value="false">Contains</option>
								<option value="true">Not Contains</option>
							</select>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Status&nbsp;:</label></div>
						<div class="listinfo_input">
							<select name="r_running">
								<option value="">All</option>
								<option value="no">Finished</option>
								<option value="yes">Running</option>
							</select>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"><label>Run Time&nbsp;:</label></div>
						<div class="listinfo_input">
								<input type="text" style="width:130px;" class="vDateField" name="r_created_since" id="id_r_created_since"/>
								<a href="javascript:DateTimeShortcuts.openCalendar(2);" id="calendarlink1"></a>
						</div>
					</div>
					<div class="listinfo">
						<div class="title"></div>
						<div class="listinfo_input">
								<input type="text" style="width:130px;" class="vDateField" name="r_created_before" id="id_r_created_since"/>
								<a href="javascript:DateTimeShortcuts.openCalendar(2);" id="calendarlink1"></a>
						</div>
					</div>
					<div class="clear"></div>
				</div>
			</div>
			<div class="clear"></div>
		</div>
		<div class="button_box">
			<input type="hidden" name="target" value="" id="inpTarget"/>
			<input type="button" value="Search Plan" id="btnSearchPlan">
			<input type="button" value="Search Case" id="btnSearchCase">
			<input type="button" value="Search Run" id="btnSearchRun">
			<input type="reset" value="Reset">
		</div>
		</form>
	</div>
{% endblock %}

src/templates/search/results.html
{% extends "tcms_base.html" %}
{% load static %}
{% block subtitle %}Advanced Search Results{% endblock %}
{% block custom_stylesheet %}
<link rel="stylesheet" type="text/css" href="{% static "style/dataTables/jquery.dataTables.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "style/dataTables/jquery.dataTables_themeroller.css" %}" />
{% endblock %}
{% block custom_javascript %}
<script type="text/javascript" src="{% static "js/lib/jquery.dataTables.js" %}"></script>
<script type="text/javascript" src="{% static "js/nitrate.advanced-search.js" %}"></script>
{% endblock %}

{% block contents %}
	<div class="sprites crumble">
		<a href="{% url "nitrate-index" %}">Home</a>
		>> <a href="{% url "advanced-search" %}">Advanced Search</a>
		>> Search Results
	</div>
	<div class="queries">
		<ul>
		{% for k, v in queries.items %}
			<li><label>{{ k|title }}:</label>{{ v|safe }};</li>
		{% endfor %}
			<li class="clear"></li>
		</ul>
		<p></p>
	</div>
	<h2 class="clear">
		Search Results<span style="font-weight:normal; font-size:12px; padding:0 0 0 15px;">Time cost: {{ time_cost }} sec(s).</span>
	</h2>

	{% if search_target == "plan" %}

	<script type="text/javascript" src="{% static "js/nitrate.testplans.js" %}"></script>
	<script type="text/javascript">
	  Nitrate.TestPlans.AdvancedSearch.numberOfPlans = {{ total_count }};
	  Nitrate.Utils.after_page_load(Nitrate.TestPlans.AdvancedSearch.on_load);
	</script>

	{% include 'plan/search_result.html' %}

	{% elif search_target == "case" %}

	<script type="text/javascript" src="{% static "js/nitrate.testcases.js" %}"></script>
	<script type="text/javascript" src="{% static "js/nitrate.toggledetail.js" %}"></script>
	<script type="text/javascript">
	  Nitrate.TestCases.Search.ActionUrls = {
		printableCasesUrl: '{% url "cases-printable" %}',
		exportCasesUrl:'{% url "cases-export" %}'
	  };
	  Nitrate.TestCases.Search.numberOfCases = {{ total_count }};
	  Nitrate.Utils.after_page_load(Nitrate.TestCases.AdvancedSearch.on_load);
	</script>

	{% include "case/search_result.html" %}

	{% elif search_target == "run" %}

	<script type="text/javascript" src="{% static "js/nitrate.testruns.js" %}"></script>
	<script type="text/javascript">
	  Nitrate.TestRuns.Search.numberOfRuns = {{ total_count }};
	  Nitrate.Utils.after_page_load(Nitrate.TestRuns.AdvancedSearch.on_load);
	</script>
	{% include "run/search_result.html" %}

	{% endif %}

{% endblock %}