src/tcms/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog

# XML RPC handler
from kobo.django.xmlrpc.views import XMLRPCHandlerFactory

from tcms.core import ajax as tcms_core_ajax
from tcms.testruns import views as testruns_views

xmlrpc_handler = XMLRPCHandlerFactory("TCMS_XML_RPC")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("", include("tcms.core.urls")),
    path("", include("tcms.management.urls")),
    # Testplans zone
    path("plan/", include("tcms.testplans.urls.plan_urls")),
    path("plans/", include("tcms.testplans.urls.plans_urls")),
    # Testcases zone
    path("case/", include("tcms.testcases.urls.case_urls")),
    path("cases/", include("tcms.testcases.urls.cases_urls")),
    # Testruns zone
    path("run/", include("tcms.testruns.urls.run_urls")),
    path("runs/", include("tcms.testruns.urls.runs_urls")),
    path("accounts/", include("tcms.profiles.urls")),
    path("linkref/", include("tcms.linkreference.urls")),
    path("comments/", include("tcms.comments.urls")),
    path("advance-search/", include("tcms.search.urls")),
    path("report/", include("tcms.report.urls")),
    path("xmlrpc/", xmlrpc_handler),
    path("tinymce/", include("tinymce.urls")),
    # Using admin js without admin permission
    # refer: https://docs.djangoproject.com/en/1.6/topics/i18n/translation/#module-django.views.i18n
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
]

# Debug zone

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

# Overwrite default 500 handler
# More details could see django.core.urlresolvers._resolve_special()
handler500 = "tcms.core.views.error.server_error"

src/tcms/comments/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django_comments.forms import CommentDetailsForm

COMMENT_MAX_LENGTH = getattr(settings, "COMMENT_MAX_LENGTH", 10000)


class SimpleForm(CommentDetailsForm):
    name = forms.CharField(
        label=_("Name"),
        widget=forms.HiddenInput,
        max_length=50,
        required=False,
    )
    email = forms.EmailField(label=_("Email address"), widget=forms.HiddenInput, required=False)
    url = forms.URLField(label=_("URL"), widget=forms.HiddenInput, required=False)
    comment = forms.CharField(
        label=_("Comment"),
        widget=forms.Textarea,
        max_length=COMMENT_MAX_LENGTH,
    )

    def clean_timestamp(self):
        # return self.cleaned_data["timestamp"]

        import time

        return str(time.time()).split(".")[0]

    def get_form(self):
        # Use our custom comment model instead of the built-in one.
        return SimpleForm

src/templates/plan/action_controls_on_cases.html
<form class="js-cases-actions" action="{% url "cases-all" %}" method="get">
	<input type="hidden" name="type" value="{% if show_confirmed_cases %}case{% else %}review_case{% endif %}" />
	<input type="hidden" name="case_sort_by" value="{{ REQUEST_CONTENTS.case_sort_by }}" />
	<input type="hidden" name="plan" value="{{ REQUEST_CONTENTS.from_plan }}" />
	<input type="hidden" name="from_plan" value="{{ REQUEST_CONTENTS.from_plan }}" />
	{# todo: seems this hidden value is still being used somewhere. Leave it here for further check. #}
	<input type="hidden" name="template_type" value="{{ REQUEST_CONTENTS.template_type }}" />
	<div class="tab_navigation actions">
		<div class='toolbar'>
			<ul>
				<li>
					{% if perms.testcases.add_testcase %}
					<span id="js-case-menu" class='sprites toolbar_case icon_plan' data-params='["{% url "cases-new" %}", {{ test_plan.plan_id }}]'>Case</span>
					{% else %}
					<span class='sprites toolbar_case icon_plan'>Case</span>
					{% endif %}
					<ul>
						{% if perms.testcases.add_testcase %}
						<li>
							<input class="add_new icon_plan js-new-case" type="button" value="Write new case" data-action-url="{% url "cases-new" %}?from_plan={{ test_plan.plan_id }}" />
						</li>
						<li>
							<input type="button" class="import icon_plan js-import-cases" value="Import cases from XML" />
						</li>
						<li>
							<input type="button" class="search icon_plan js-add-case-to-plan" value="Add cases from other plans"
								data-action-url="{% url "plan-search-cases-for-link" test_plan.plan_id %}" />
						</li>
						{% else %}
						<li><input type="button" class="add_new icon_plan" disabled value="Write new case" /></li>
						<li><input type="button" class="import icon_plan" disabled value="Import cases from XML" /></li>
						<li><input type="button" class="search icon_plan" disabled value="Add cases from other plans" /></li>
						{% endif %}
						<li>
							<input type="button" class="export icon_plan js-export-cases" value="Export"
								title="Export selected cases into XML file" data-action-url="{% url "cases-export" %}" />
						</li>
						<li>
							<input type="button" class="print_view icon_plan js-print-cases" value="Print"
								title="print view of selected cases" data-action-url="{% url "cases-printable" %}" />
						</li>
						{% if perms.testcases.add_testcase %}
						<li>
							<input type="button" class="clone icon_plan js-clone-cases" value="Clone"
								title="Clone selected cases to another test plan" data-action-url="{% url "cases-clone" %}" />
						</li>
						{% else %}
						<li>
							<input type="button" class="clone icon_plan" value="Clone"
								title="Clone selected cases to another test plan" disabled />
						</li>
						{% endif %}
						{% if perms.testcases.delete_testcaseplan %}
						<li>
							<input type="button" class="delete icon_plan js-remove-cases" value="Remove"
								title="Remove selected cases from this plan" />
						</li>
						{% else %}
						<li>
							<input type="button" class="delete icon_plan" value="Remove"
								title="Remove selected cases from this plan" disabled />
						</li>
						{% endif %}
						{% if perms.testcases.change_testcase %}
						<li>
							<input type="button" class="sort_list icon_plan" value="Set Sort Number"
								title="Set sort number of selected cases from this plan" />
						</li>
						{% else %}
						<li>
							<input type="button" class="sort_list icon_plan" value="Set Sort Number"
								title="Set sort number of selected cases from this plan" disabled />
						</li>
						{% endif %}
					</ul>
				</li>

				{% if show_confirmed_cases %}
				<li>
					<span class='sprites toolbar_run {% if not perms.testruns.add_testrun %}toolbar_run_disabled{% endif %} icon_plan'>Run</span>
					<ul>
						{% if perms.testruns.add_testrun %}
						<li>
							<input type="button" class="new_run icon_plan js-new-run" value="Write a new run" data-action-url="{% url "run-new" %}" />
						</li>
						<li>
							<input type="button" class="search icon_plan js-add-case-to-run" value="Add cases to run" data-action-url="{% url "plan-choose-run" test_plan.plan_id %}" />
						</li>
						{% else %}
						<li>
							<input type="button" class="new_run icon_plan" value="Write a new run" disabled />
						</li>
						<li><input type="button" class="search icon_plan" value="Add cases to run" disabled /></li>
						{% endif %}
					</ul>
				</li>
				{% endif %}

				<li>
					<span class='sprites toolbar_tag {% if not perms.testcases.add_testcasetag %}toolbar_tag_disabled{% endif %} icon_plan'>Tag</span>
					<ul>
						{% if perms.testcases.add_testcasetag %}
						<li><input type="button" value="Add Tag" class="tag_add sprites icon_plan" /></li>
						{% else %}
						<li><input type="button" value="Add Tag" class="tag_add_disabled sprites icon_plan" disabled /></li>
						{% endif %}
						{% if perms.testcases.delete_testcasetag %}
						<li><input type="button" value="Remove Tag" class="tag_delete sprites icon_plan" /> </li>
						{% else %}
						<li><input type="button" value="Remove Tag" class="tag_delete_disabled sprites icon_plan" disabled /></li>
						{% endif %}
					</ul>
				</li>

				{% if perms.testcases.change_testcase %}
				<li>
					<input type="button" value="Automated" title="change automated" class="btn_automated automated sprites icon_plan" />
				</li>
				{% if show_confirmed_cases %}
				<li>
					<input type="button" value="Default Tester" title="change default tester"
						class="btn_default_tester assignee sprites icon_plan" />
				</li>
				{% else %}
				<li>
					<input type="button" value="Reviewer" title="change reviewer" class="btn_reviewer assignee sprites icon_plan" />
				</li>
				{% endif %}
				<li>
					<input type="button" value="Component" class="btn_component sprites component icon_plan" />
				</li>
				<li><span class='sprites toolbar_status icon_plan'>Status</span>
					<ul>
						{% for cs in case_status %}
						<li>
							<input type='button' value='Set {{ cs }}' class='btn_case_status {{ cs|lower }} icon_plan js-status-item' data-status-id="{{ cs.pk }}" />
						</li>
						{% endfor %}
					</ul>
				</li>
				<li>
					<input type="button" value="Category" class="btn_category sprites category icon_plan" />
				</li>
				<li>
					<span class='sprites toolbar_priority icon_plan'>Priority</span>
					<ul>
						{% for priority in priorities %}
						<li>
							<input type='button' value='Set {{ priority }}' class='btn_case_priority {{ priority|lower }} icon_plan js-priority-item' data-priority-id="{{ priority.pk }}" />
						</li>
						{% endfor %}
					</ul>
				</li>
				{% else %}
				<li>
					<input type="button" value="Automated" title="change automated"
						class="btn_automated automated_disabled sprites icon_plan" disabled />
				</li>
				{% if show_confirmed_cases %}
				<li>
					<input type="button" value="Default tester" title="change default tester"
						class="btn_default_tester assigneedisable sprites icon_plan" disabled />
				</li>
				{% else %}
				<li>
					<input type="button" value="Reviewer" title="change reviewer"
						class="btn_reviewer assigneedisable sprites icon_plan" disabled />
				</li>
				{% endif %}
				<li>
					<input id="id_batch_component" type="button" value="Component"
						class="btn_component sprites component_disabled icon_plan" disabled />
					</li>
				{% endif %}
			</ul>
			<span class="reorder_case">
				<a class="btn_filter filtercase" title="Click to toggle filter options">Toggle filter options</a>
				{% if perms.testcases.change_testcase %}
				<a class="btn_sort sortlink" title="Click me,then Drag and drop the rows to adjust the order,and click 'Done Sorting' link to submit your changes">Re-order cases</a>
				{% endif %}
			</span>
		</div>
		<div class="mixbar fixed">
			<div class="tit" style="width: 50px; float: left; height: 100%; margin: 0px; text-align: center;">Tags:</div>
			<div style="margin-left: 50px; line-height:22px;" class="taglist">
				{% for tag in case_own_tags %}
				<a href="javascript:void(0)">{{ tag.tag_name }}</a>&nbsp;&nbsp;<span class="grey">-</span>&nbsp;&nbsp;
				{% empty %}
				<span class="grey">No tags in cases</span>
				{% endfor %}
			</div>
		</div>
	</div>

	<div class="list_filter" {% if REQUEST_CONTENTS.a != 'search' %}style="display:none;"{% endif %}>
		{% include "case/form/filter.html" %}
		<div class="submit-row bottom">
			<span class="tit"><span class="js-number-of-loaded-cases">{{ total_cases_count }}</span> Cases</span>
			<input type="submit" value="Filter cases" />
		</div>
	</div>
</form>

src/templates/plan/all.html
{% extends "tcms_base.html" %}

{% load extra_filters %}
{% load static %}

{% block subtitle %}Test plans{% endblock %}

{% block custom_stylesheet %}
<link rel="stylesheet" type="text/css" href="{% static "style/print.css" %}" media="print" />
<link rel="stylesheet" type="text/css" href="{% static "style/dataTables/jquery.dataTables.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "style/dataTables/jquery.dataTables_themeroller.css" %}" />
{% endblock %}

{% block custom_javascript %}
<script type="text/javascript" src="{% static "js/lib/jquery.dataTables.js" %}"></script>
<script type="text/javascript" src="{% static "js/nitrate.testplans.js" %}"></script>
<script type="text/javascript" src="/jsi18n/"></script>
<script type="text/javascript" src="{% static "admin/js/core.js" %}"></script>
<script type="text/javascript" src="{% static "admin/js/calendar.js" %}"></script>
<script type="text/javascript" src="{% static "admin/js/admin/DateTimeShortcuts.js" %}"></script>

<script type="text/javascript">
Nitrate.Utils.after_page_load(Nitrate.TestPlans.List.on_load);
Nitrate.TestPlans.List.numberOfPlans = {{ plans_count }};
</script>
{% endblock %}

{% block contents %}
<div id="content">
	<div class="sprites crumble">
		<a href="{% url "nitrate-index" %}">Home</a>
		>> <a href="{% url "plans-all" %}?is_active=on">Planning</a>
		>> Search result
	</div>
	<div id="itemSearch" class="itemSearch">
		<form id="id_search_plan_form" action="{% url "plans-all" %}" method="get">
			<input type="hidden" name="action" value="search" />
			<h2>Search Plan</h2>
			{% include 'plan/form/search.html' %}
			<div class="bottom">
				<input type="submit" size="7" value="Search" class="left_float" />
				<input type="reset" size="7" value="Reset" title="Reset the form" class="left_float" />
				<div class="allSearch">
					<a title="list all the plans" href="?name=&author=&product_id=&env_group_id=&is_active=on">View All Plans</a><span>
					|
					</span><a href="{% url "advanced-search" %}">Advanced Search</a>
				</div>
			</div>
			<div class="clear"></div>
		</form>
	</div>
	{% include 'plan/search_result.html' %}
</div>
{% endblock %}

src/templates/plan/attachment.html
{% extends "tcms_base.html" %}
{% load static %}

{% block subtitle %} {{ test_plan.name }}{% endblock %}

{% block custom_stylesheet %}
<link rel="stylesheet" type="text/css" href="{% static "style/print.css" %}" media="print" />
{% endblock %}

{% block custom_javascript %}
<script type="text/javascript" src="{% static "js/nitrate.testplans.js" %}"></script>
<script type="text/javascript" src="{% static "js/nitrate.testcases.js" %}"></script>
<script type="text/javascript" src="{% static "js/nitrate.attachments.js" %}"></script>
<script type="text/javascript">
Nitrate.Utils.after_page_load(Nitrate.TestPlans.Attachment.on_load);
Nitrate.Utils.after_page_load(Nitrate.Attachments.on_load);
</script>
{% endblock %}

{% block contents %}

<div id="content">
	<div class="sprites crumble">
		<a href="{% url "nitrate-index" %}">Home</a>
		>> <a href="{% url "plans-all" %}?is_active=on">Planning</a>
		>> <a href="{{ test_plan.get_absolute_url }}">{{ test_plan.name }}</a>
		>> Add Attachment
	</div>
	<h2 id="display_title" style="line-height:1.2em;">{{ test_plan.name }}</h2>
	<div class="Detailform border-1">
		<form action="{% url "upload-file" %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
			<div class="mixbar">
				<span class="tit">Upload New Attachment</span>
				<input type="hidden" name="to_plan_id" value="{{ test_plan.pk }}" />
				<input type="file" name="upload_file" id="upload_file" limit="{{ limit }}"/>
				<input type="submit" value="Upload" />
				<input type="button" class="js-back-button" value="Back" />
				<span class="right-action">Note: Each attachment size limit is {{ limit_readable }}.</span>
			</div>
		</form>

		{% include "plan/attachments_table.html" with attachments=test_plan.attachments.all from="from_plan" object_id=test_plan.pk %}
	</div>
</div>

{% endblock %}

src/templates/plan/attachments_table.html
{% comment %}
Arguments:
attachments: a list of attachments to display.
from: a string to indicate the object type, from_case or from_plan.
object_id: the object id the attachments are associated with.
{% endcomment %}
<table id="attachments" class="list" cellspacing="0" cellspan="0">
	<thead>
	<tr>
		<th align="left">File name</th>
		<th align="left" width="10%">Submitter</th>
		<th align="left" width="20%">Create date</th>
		<th align="left" width="20%">Mimetype</th>
		<th align="left" width="10%">Action</th>
	</tr>
	</thead>
	<tbody>
	{% for attachment in attachments %}
		<tr id="{{ attachment.pk }}" class="{% cycle 'odd' 'even' %}">
			<td><a href="{% url "check-file" attachment.pk %}">{{ attachment.file_name }}</a></td>
			<td>{{ attachment.submitter }}</td>
			<td>{{ attachment.create_date }}</td>
			<td>{{ attachment.mime_type }}</td>
			<td>
				<a href="{% url "check-file" attachment.pk %}">View</a>
				{% if perms.management.delete_testattachment %}
				|
				<a class="js-remove" href="javascript:void(0)"
					data-attachment-id="{{ attachment.pk }}" data-from="{{ from }}" data-object-id="{{ object_id }}"
				>Delete</a>
				{% endif %}
			</td>
		</tr>
		{% empty %}
		<tr><td colspan="5" align="center"><span class="grey">No attachments</span></td></tr>
	{% endfor %}
	</tbody>
</table>

src/templates/plan/choose_testrun.html
{% extends "tcms_base.html" %}

{% load static %}

{% block subtitle %}Choose test run to assign case{% endblock %}

{% block custom_stylesheet %}
{% endblock %}

{% block custom_javascript %}
<script type="text/javascript" src="{% static "js/nitrate.testruns.js" %}"></script>
<script type="text/javascript" src="{% static "js/nitrate.toggledetail.js" %}"></script>
<script type="text/javascript">
Nitrate.Utils.after_page_load(Nitrate.TestRuns.ChooseRuns.on_load);
</script>
{% endblock %}

{% block contents %}
<div id="content">
	<div class="sprites crumble">
		<a href="{% url "nitrate-index" %}">Home</a>
		&gt;&gt; <a href="{% url "plans-all" %}?is_active=on">...</a>
		&gt;&gt; <a href="{{ plan.get_absolute_url }}">[{{ plan.plan_id }}]{{ plan.name }}</a>
		&gt;&gt; Add test case to runs
	</div>
	<h2 id="display_title"><a href="{{ plan.get_absolute_url }}">Plan:{{ plan.name }}</a></h2>
	<form method="post" onsubmit="return window.confirm('Are you sure to add cases to the run?')">{% csrf_token %}
		<table id="id_table_runs" class="list" cellpadding="0" cellspacing="0" border="0">
			<thead>
				<tr>
					<th class="nosort" align="left" width="20px"><input id="id_check_all_button" type="checkbox" /></th>
					<th class="sortcol widthID" align="left">TestRun ID</th>
					<th class="sortcol">Test Run Summary</th>
					<th class="sortcol" width="230">Build</th>
					<th class="sortcol" width="120">Manager</th>
					<th class="sortcol" width="270">Test Plan</th>
				</tr>
			</thead>
			<tbody>
				{% for test_run in test_runs %}
				<tr id="row_{{ forloop.counter }}" class="{% cycle 'odd' 'even' %} selection_row">
					<td align="center">
						{# Hide the check box when it is in the exist_case_runs, and remove it from form submitation #}
						<input type="checkbox" name="run" value="{{ test_run.pk }}"/>
					</td>
					<td>
						<a href="{% url "run-get" test_run.pk %}">{{ test_run.pk }}</a>
					</td>
					<td>
						{{ test_run.summary }}
					</td>
					<td>{{ test_run.build__name }}</td>
					<td><a href="{% url "user-profile" test_run.manager__username %}">{{ test_run.manager__username }}</a></td>
					<td>{{ plan.name }}</td>
				</tr>
				{% empty %}
				<tr><td colspan="6">This plan has no test runs.</td></tr>
				{% endfor %}
			</tbody>
		</table>
		<div class="Detailform border-1" id="testcases_selected">
			<div class="mixbar">
				<span class="tit" width="150px"><b>Cases to be added: {{ test_cases|length }}</b></span>
				<input type="submit" value="Update" title="Update the cases in this run" />
				<input type="reset" value="Reset" title="Reset to the original cases "/>
				<span class="right-action">
					<a class="helplink js-help-info" id="" title="view the help information about assigning case">How to Assign case?</a>
				</span>
			</div>
			<div class="Detailform system_info border-1" id="help_assign" style="display:none">
				<div class="Detailform-variety_1">
					<p>
						The table below list all the confirmed test case of plan {{ test_run.plan }}, check the checkbox to add the case into the test run, uncheck it to remove from the test run, remember to update at last.
						<span class="right-action">
							<a href="#" class="js-close-help">X</a>
						</span>
					</p>
				</div>
			</div>
			<table id="id_table_cases" class="list" cellpadding="0" cellspacing="0" border="0">
				<thead>
					<tr>
						<th class="nosort" align="left" width="20px"></th>
						<th class="sortcol widthID" align="left">ID</th>
						<th class="sortcol">Test Case Summary</th>
						<th class="sortcol" width="130">Author</th>
						<th class="sortcol" width="150">Created Date</th>
						<th class="sortcol" width="150">Category</th>
						<th class="sortcol"  width="70">Priority</th>
						<th class="sortcol" width="70">Sort Key</th>
						<th class="sortcol"  width="70">Selected</th>
					</tr>
				</thead>
				<tbody>
					{% for test_case in test_cases %}
					<tr id="row_{{ forloop.counter }}" class="{% cycle 'odd' 'even' %} selection_row js-one-case">
						<td>
							<a id="blind_link_{{ forloop.counter }}" class="blind_link js-toggle-button" href="javascript:void(0);" data-param="{{ forloop.counter }}">
								<img id="blind_icon_{{ forloop.counter }}" class="blind_icon" src="{% static "images/t1.gif" %}" border="0" alt="">
							</a>
						</td>
						<td>
							<a href="{% url "case-get" test_case.pk %}">{{ test_case.pk }}</a>
							<input type="hidden" name="case" value="{{ test_case.pk }}" />
						</td>
						<td class="js-one-case" data-param="{{ forloop.counter }}">
							<a id="link_{{ forloop.counter }}" class="blind_title_link" href="javascript:void(0);">
								{{ test_case.summary }}
							</a>
						</td>
						<td><a href="{% url "user-profile" test_case.author__username %}">{{ test_case.author__username }}</a></td>
						<td>{{ test_case.create_date }}</td>
						<td>{{ test_case.category__name }}</td>
						<td>{{ test_case.priority__value }}</td>
						<td>{{ test_case.sortkey }}</td>
						<td></td>
					</tr>
					<tr id="hidenRow_{{ forloop.counter }}" class="Detailform border-1 hide" style="display: none;">
						<td colspan="9" id="id_case_text_{{ forloop.counter }}">
							<div class="ajax_loading"></div>
						</td>
					</tr>
					{% empty %}
					<tr>
						<td colspan="10">No test cases selected.</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</form>
</div>

{% endblock %}

src/templates/plan/clone.html
{% extends "tcms_base.html" %}
{% load static %}

{% block subtitle %}Clone Plan{% endblock %}

{% block custom_stylesheet %}
{% endblock %}

{% block custom_javascript %}
<script type="text/javascript" src="{% static "js/nitrate.index.js" %}"></script>
<script type="text/javascript" src="{% static "js/nitrate.testplans.js" %}"></script>
<script type="text/javascript">
Nitrate.Utils.after_page_load(Nitrate.TestPlans.Clone.on_load);
</script>
{% endblock %}

{% block contents %}

<div id="content">
	<div class="sprites crumble">
		<a href="{% url "nitrate-index" %}">Home</a>
		>> <a href="{% url "plans-all" %}?is_active=on">Planning</a>
		{% if testplans|length == 1 %}
		>> <a href="{{ testplans.0.get_absolute_url }}">{{ testplans.0.plan_id }}: {{ testplans.0.name }}</a>
		>> Clone Plan
		{% else %}
		>> Clone plans
		{% endif %}
	</div>
	<h2>Clone Test Plan</h2>
	<p class="help">
		select different product
	</p>
	<div class="Detailform border-1">
		<form action="{% url "plans-clone" %}" method="post">{% csrf_token %}
			{% for testplan in testplans %}
			<input type="hidden" name="plan" value="{{ testplan.pk }}" />
			{% endfor %}
			<table	class="editor" cellspacing="0" cellspan="0">
				<tr>
					{% if testplans|length == 1 %}
					<td width="20%"><label class="strong" for="id_name">New Plan Name</label> </td>
					<td class="name">{{ clone_form.name }}</td>
					{% else %}
					<td width="20%">
						<label class="strong">Plans</label>
						<span class="help">Note:Can't change plan name when clone multiple plans, you can edit them after cloned.</span>
					 </td>
					<td class="name">
						<ul class="ul-no-format">
							{% for testplan in testplans %}
							<li>
								<span class="lab-50">{{ testplan.plan_id }}</span>
								<span class="lab-100">{{ testplan.type }}</span>
								<span>
									<a href="{{ test_plan.get_absolute_url }}" title="{{ testplan.name }} ({{ testplan.author.email }})">
									 {{ testplan.name }}
									</a>
								</span>
							</li>
							{% endfor %}
						</ul>
					</td>
					{% endif %}
				</tr>
				<tr>
					<td><label class="strong" for="id_product_id">Copy to Product</label></td>
					<td>{{ clone_form.product }}</td>
				</tr>
				<tr>
					<td><label class="strong" for="id_version_id">Product Version</label></td>
					<td>
						{{ clone_form.product_version }}
						<span class="errors">{{ clone_form.product_version.errors }}</span>
					</td>
				</tr>
				<tr>
					<td><label class="strong">Copy Settings</label> </td>
					<td>
						<ul class="ul-no-format">
							<li>{{ clone_form.set_parent }}{{ clone_form.set_parent.label }} ({{ clone_form.set_parent.help_text }})</li>
							<li>{{ clone_form.keep_orignal_author }}{{ clone_form.keep_orignal_author.label }} ({{ clone_form.keep_orignal_author.help_text }})</li>
							<li>{{ clone_form.copy_texts }}{{ clone_form.copy_texts.label }} ({{ clone_form.copy_texts.help_text }})</li>
							<li>{{ clone_form.copy_attachements }}{{ clone_form.copy_attachements.label }} ({{ clone_form.copy_attachements.help_text }})</li>
							<li>{{ clone_form.copy_environment_group }}{{ clone_form.copy_environment_group.label }} ({{ clone_form.copy_environment_group.help_text }})</li>
							<li>
								<fieldset class="choose">
									<legend>{{ clone_form.link_testcases }}Copy {{ clone_form.link_testcases.label }}</legend>
									<ul id="id_clone_case_zone" style="display:block ;list-style-type:none;">
										<li>{{ clone_form.copy_testcases }}{{ clone_form.copy_testcases.label }} ({{ clone_form.copy_testcases.help_text }})</li>
										<li>{{ clone_form.maintain_case_orignal_author }}{{ clone_form.maintain_case_orignal_author.label }} ({{ clone_form.maintain_case_orignal_author.help_text }})</li>
										<li>{{ clone_form.keep_case_default_tester }}{{ clone_form.keep_case_default_tester.label }} ({{ clone_form.keep_case_default_tester.help_text }})</li>
									</ul>
								</fieldset>
							</li>
						</ul>
					</td>
				</tr>
			</table>
			<div class="submit-row">
				<input type="submit" name="submit" value="Clone" />
				<input type="button" value="Cancel" class="js-cancel-button" />
			</div>
		</form>
	</div>
</div>
{% endblock %}